# Generated by Django 2.2.5 on 2021-11-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211118_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
