# Generated by Django 2.2.5 on 2021-11-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
