# Generated by Django 2.2.5 on 2021-11-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211123_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='stu_id',
            field=models.IntegerField(default=False),
        ),
    ]
