# Generated by Django 2.2.5 on 2021-11-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='room',
        ),
    ]
