# Generated by Django 2.2.5 on 2021-11-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_auto_20211123_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='cat_photos'),
        ),
    ]
