# Generated by Django 2.2.5 on 2021-11-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0004_auto_20211123_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='input',
            name='file',
            field=models.ImageField(blank=True, upload_to='cat_photos'),
        ),
    ]
