# Generated by Django 2.2.5 on 2021-11-24 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('cat_name', models.CharField(choices=[('학치', '학치'), ('삐약이', '삐약이'), ('목주', '목주'), ('모름', '모름')], max_length=4)),
                ('description', models.TextField()),
                ('file', models.ImageField(blank=True, null=True, upload_to='cat_photos')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
