# Generated by Django 2.2.5 on 2021-12-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20211216_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.ImageField(default=False, upload_to='cat_photos'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
