# Generated by Django 2.2.5 on 2021-12-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20211218_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
