# Generated by Django 2.2.5 on 2021-12-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20211224_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='cat_photos'),
        ),
    ]
